import { PerfImg } from "../assets";

const ShopItemData = [
  {
    id: "1",
    name: "alexander-tsang",
    price: 45,
    count: 0,
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing.",
    img: PerfImg.alexander,
  },
  {
    id: "2",
    name: "allison-pieterse",
    price: 100,
    count: 0,
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing.",
    img: PerfImg.allison,
  },
  {
    id: "3",
    name: "charles-deluvio",
    price: 25,
    count: 0,
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing.",
    img: PerfImg.charlesdeluvio,
  },

  {
    id: "4",
    name: "dario-gomes",
    price: 300,
    count: 0,
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing.",
    img: PerfImg.dario,
  },

  {
    id: "5",
    name: "fernando-andrade",
    price: 300,
    count: 0,
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing.",
    img: PerfImg.fernando,
  },

  {
    id: "6",
    name: "heidi-walley",
    price: 300,
    count: 0,
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing.",
    img: PerfImg.heidi,
  },
  {
    id: "7",
    name: "jeroen-den-otter",
    price: 300,
    count: 0,
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing.",
    img: PerfImg.jeroen,
  },
  {
    id: "8",
    name: "karly-jones",
    price: 300,
    count: 0,
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing.",
    img: PerfImg.karly,
  },
  {
    id: "9",
    name: "kelvin-lutan",
    price: 300,
    count: 0,
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing.",
    img: PerfImg.kelvin,
  },
  {
    id: "10",
    name: "laura-chouette",
    price: 300,
    count: 0,
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing.",
    img: PerfImg.laura,
  },
  {
    id: "11",
    name: "mae-mu",
    price: 300,
    count: 0,
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing.",
    img: PerfImg.mae,
  },
  {
    id: "12",
    name: "nusiba-ahmed",
    price: 300,
    count: 0,
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing.",
    img: PerfImg.nusiba,
  },
  {
    id: "13",
    name: "pesce-huang",
    price: 300,
    count: 0,
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing.",
    img: PerfImg.pesce,
  },
  {
    id: "14",
    name: "rosy-h-nguyen",
    price: 300,
    count: 0,
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing.",
    img: PerfImg.rosy,
  },
  {
    id: "15",
    name: "ruijia-wang",
    price: 300,
    count: 0,
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing.",
    img: PerfImg.ruijia,
  },
  {
    id: "16",
    name: "won-young-park",
    price: 300,
    count: 0,
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing.",
    img: PerfImg.won,
  },
  {
    id: "17",
    name: "yixian-zhao",
    price: 300,
    count: 0,
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing.",
    img: PerfImg.yixian,
  },
  {
    id: "18",
    name: "laura-chouette2",
    price: 300,
    count: 0,
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing.",
    img: PerfImg.laura2,
  },
];
export default ShopItemData;
